completed all the tasks of lesson 2
Tot741/geekshop_server pull request #2
Opened 2021-01-24 21:41 UTC by Tot741

2021-01-25 15:11 UTC, Vokler requested changes

2021-01-25 15:11 UTC, Vokler commented on mainapp/templates/mainapp/products.html
> +                                     src="{% static '' %}{{product.src}}"
Лучше так не делать, а заменить на `{% static product.src %}`

2021-01-25 15:11 UTC, Vokler commented on mainapp/views.py
> +    with open("mainapp/fixtures/products.json", "r") as json_data:
Следите за единым стилем кавычек

2021-01-25 16:28 UTC, Tot741 commented on mainapp/templates/mainapp/products.html
> +                                     src="{% static '' %}{{product.src}}"
Ну я так и думал что это неправильно, но я доделывал в 2 ночи и почему-то пробовал написать {% static 'product.src' %}, конечно оно не работало ))
Исправил. Мне нужно заново пул реквест сделать или как? Commit&push я сделал

2021-01-25 16:28 UTC, Tot741 commented on mainapp/views.py
> +    with open("mainapp/fixtures/products.json", "r") as json_data:
Да, обычно стараюсь, тут пропустил. Тоже поправил. Спасибо

2021-01-26 19:50 UTC, Vokler approved these changes

2021-01-26 19:50 UTC, merged